"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
pager = ":builtin"
default-command = "log"

[user]
name = "Antti Kupila"
email = "akupila@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
sign-on-push = true
