---@meta
-- Hand-written companion to types.lua, which is generated by `jjui -install-lua-types`
-- and does not yet cover setup()/config. Safe from regeneration.

---@class jjui.config
---@field action fun(name: string, fn: fun(), opts?: jjui.config.action_opts) Register a Lua action, optionally with an inline binding
---@field bind fun(opts: jjui.config.bind_opts) Bind a key to an action defined elsewhere

---@class jjui.config.action_opts
---@field key? string|string[] Key or keys; mutually exclusive with seq
---@field seq? string|string[] Key sequence; mutually exclusive with key
---@field scope? string Required when key or seq is set
---@field desc? string Description shown in the status bar

---@class jjui.config.bind_opts
---@field action string Action name or built-in action ID
---@field scope string Where the binding is active
---@field key? string|string[] Key or keys; set exactly one of key or seq
---@field seq? string|string[] Key sequence; set exactly one of key or seq
---@field desc? string Label shown in the help and status bar
---@field args? table Arguments for built-in actions

---Called by jjui at startup to register actions and bindings.
---@param config jjui.config
function setup(config) end
